/* eslint-disable prettier/prettier */
import type {
  Content,
  StyleDictionary,
  TDocumentDefinitions,
} from 'pdfmake/interfaces';
import type { Clientes } from '../entities/users.entity';

const fechaActual = new Date();

const logo: Content = {
  image: 'src/assets/mylogo.png',
  width: 60,
};

const styles: StyleDictionary = {
  h1: {
    fontSize: 20,
    bold: true,
    margin: [0, 5],
  },
  h2: {
    fontSize: 16,
    bold: true,
  },
  h3: {
    fontSize: 14,
    bold: true,
  },
};

export const billReport = (Clientes: Clientes[], nombre: string): TDocumentDefinitions => {
  return {
    defaultStyle: {
      // fontSize: 8,
    },
    pageSize: 'A4',
    header: function (currentPage, pageCount) {
      return {
        text: `Página ${currentPage} de ${pageCount}`,
        alignment: 'right',
        margin: [20, 10, 20, 0],
      };
    },
    footer: {
      text: 'Generated by Luis Hernando ML',
      alignment: 'right',
      margin: [10, 10],
    },
    content: [
      logo,

      // Linea de separación
      {
        canvas: [
          {
            type: 'line',
            x1: 0,
            y1: 5,
            x2: 515,
            y2: 5,
            lineWidth: 1,
          },
        ],
      },

      {
        text: 'Enterprise Users report',
        style: 'h1',
      },

      // Dirección de la empresa columna #1
      {
        columns: [
          {
            text: [
              { text: 'Medellin Colombia.\n', style: 'h3' },
              `Calle 10 Cra 30 \nBN: 123456789\n`,
              {
                link: 'https://aulavirtual.uniremington.edu.co',
                text: 'https://tarea3.com',
              },
            ],
          },
          {
            text: [
              { text: 'Inform Number: 123456\n', style: 'h3' },
              `Date: ${fechaActual.getFullYear()}-${fechaActual.getMonth() + 1}-${fechaActual.getDate()}\nDue Date: ${fechaActual.getFullYear()}-${fechaActual.getMonth() + 2}-${fechaActual.getDate()}`,
            ],
            alignment: 'right',
          },
        ],
      },

      // Código QR con la dirección
      {
        qr: 'https://aulavirtual.uniremington.edu.co',
        fit: 100,
        alignment: 'right',
      },

      // Datos del cliente
      {
        text: [
          {
            text: 'Generado Por:\n',
            style: 'h2',
          },
          `${nombre}\nRazón Social: John Doe Cop.\nBN: 123456789`,
        ],
      },

      // Tabla con los datos del pedido
      {
        margin: [0, 20],
        layout: 'lightHorizontalLines',
        table: {
          widths: [50, '*', 'auto', 'auto', 'auto', 'auto'],
          headerRows: 1,
          body: [
            [
              { text: 'ID', alignment: 'center' },
              'Nombre',
              'Correo',
              'Telefono',
              'Direccion',
              'Ciudad',
            ],
            ...Clientes.map((client) => [
              { text: client.id, alignment: 'center' },
              client.Nombre,
              client.Correo,
              client.Telefono,
              client.Direccion,
              client.ciudad,
            ]),

            // Totales de la tabla
          ],
        },
      },
    ],
    styles: styles,
  };
};
